routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'OrderController@index');

    Route::resource('order', 'OrderController');

    Route::resource('product', 'ProductController');

    Route::get('logout', function (){
        Auth::logout();
        return redirect('/');
    });

    Route::get('password', 'OrderController@password');
	Route::post('password', 'OrderController@updatePassword');

});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function product(){
        return $this->belongsTo('App\Product');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use App\Order;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;

use App\User;
use Hash;
use Validator;
use Auth;


class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::all();
        return view('order/index')->with( 'orders', $orders );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = Product::pluck('product_name','id')->prepend('Seleccionar alimento','');
        return view('order/new')->with('product', $product);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = new Order();

        $order->name = Input::get('name');
        $order->phone = Input::get('phone');
        $order->address = Input::get('address');
        $order->delivery_date = Input::get('delivery_date');
        $order->product_id = Input::get('product_id');
        $order->payment_option = Input::get('payment_option');
        $order->quantity = Input::get('quantity');
        $order->order_status = Input::get('order_status');

        if($order->save())
        {
            Session::flash('message','Pedido creado correctamente');
            Session::flash('m-class','alert-success');
            return redirect('order');
        }
        else
        {
            Session::flash('message','Pedido no guardado');
            Session::flash('m-class','alert-danger');
            return redirect('order/create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        return view('order/show')->with('order', $order);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);
        $product = Product::pluck('product_name','id');
        return view('order/edit')->with(['order' => $order,'product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::find($id);

        $order->name = Input::get('name');
        $order->phone = Input::get('phone');
        $order->address = Input::get('address');
        $order->delivery_date = Input::get('delivery_date');
        $order->product_id = Input::get('product_id');
        $order->payment_option = Input::get('payment_option');
        $order->quantity = Input::get('quantity');
        $order->order_status = Input::get('order_status');

        if($order->save())
        {
            Session::flash('message','Pedido actualizado correctamente');
            Session::flash('m-class','alert-success');
            return redirect('order');
        }
        else
        {
            Session::flash('message','Data is not saved');
            Session::flash('m-class','alert-danger');
            return redirect('order/create');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Order::find($id)->delete();

        Session::flash('message','Pedido eliminado correctamente');
        Session::flash('m-class','alert-success');
        return redirect('order');
    }

    //UPDATE Password
    public function password(){
        return View('password');
    }

    public function updatePassword(Request $request){
        $rules = [
            'mypassword' => 'required',
            'password' => 'required|confirmed|min:6|max:18',
        ];
        
        $messages = [
            'mypassword.required' => 'Contraseña actual es requerida',
            'password.required' => 'Nueva contraseña es requerida',
            'password.confirmed' => 'Las contraseñas no concuerdan',
            'password.min' => 'Contraseña muy corta (mínimo 6 caracteres)',
            'password.max' => 'Contraseña muy larga (máximo 18 caracteres)',
        ];
        
        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()){
            return redirect('password')->withErrors($validator);
        }
        else{
            if (Hash::check($request->mypassword, Auth::user()->password)){
                $user = new User;
                $user->where('email', '=', Auth::user()->email)
                     ->update(['password' => bcrypt($request->password)]);
                return redirect('/')->with('message', 'Contraseña cambiada correctamente')->with('m-class','alert-success');
            }
            else
            {
                return redirect('password')->with('message', 'Contraseña inválida')->with('m-class','alert-danger');
            }
        }
    }
}

resources/views/order/edit.blade.php
@extends('layouts.app')

@section('title')
    Editar pedido
@endsection


@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="index.html"><i class="fa fa-home"></i> Inicio</a></li>
            <li class="active">#</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Editar</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                Editar pedido
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>

            <div class="panel-body">
                {!! Form::model($order, array('method'=>'PATCH','route' => array('order.update', $order->id))) !!}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Nombre completo</label>
                            {!! Form::text('name', null, ['placeholder'=>'Ingrese su nombre completo', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>CI / NIT</label>
                            {!! Form::text('phone', null, ['placeholder'=>'Ingrese su CI /NIT', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Dirección</label>
                            {!! Form::textarea('address', null, ['placeholder'=>'Ingrese su dirección', 'class'=>'form-control input-lg','rows'=>'3','required']) !!}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Fecha</label>
                            {!! Form::date('delivery_date', null, [ 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Menu</label>
                            {!! Form::select('product_id', $product, null, ['id'=>'product_id', 'class'=>'form-control m-b input-lg','required']) !!}
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Tipo</label>
                                    {!! Form::select('payment_option', array( 'Mesanine' => 'Mesanine', 'Para llevar' => 'Para llevar'), null, ['class'=>'form-control m-b input-lg','required']) !!}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Cantidad</label>
                                    {!! Form::number('quantity', null, ['placeholder'=>'Ingrese cantidad', 'class'=>'form-control input-lg','required']) !!}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        <div class="row">
                            <div class="form-group">
                                <label class="col-sm-2">Status</label>
                                <div class="col-sm-10 ">
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Confirm') !!}<i class="fa fa-circle-o fa-1x"></i>Confirm </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Ready') !!}<i class="fa fa-circle-o"></i>Item Ready </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Send') !!}<i class="fa fa-circle-o"></i>Send </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Delivered') !!}<i class="fa fa-circle-o"></i>Delivered </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Returned') !!}<i class="fa fa-circle-o"></i>Returned </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Cancelled') !!}<i class="fa fa-circle-o"></i>Cancelled </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        {!! Form::submit('Submit', [ 'class'=>'btn btn-default']) !!}
                    </div>
                {!! Form::close() !!}
            </div>

        </section>
    </section>
</section>

@endsection

resources/views/order/index.blade.php
@extends('layouts.app')

@section('title')
    Pedidos
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="{{url('/')}}"><i class="fa fa-home"></i> Inicio</a></li>
            <li class="active">#</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Pedidos</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                Todos los pedidos
                <button onClick ="$('#table').tableExport({type:'pdf',escape:'false',pdfFontSize:12,separator: ','});" class="btn btn-default btn-xs pull-right">PDF</i></button>
                
                <button onClick ="$('#table').tableExport({type:'excel',escape:'false'});" class="btn btn-default btn-xs pull-right">Excel</i></button>
                
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>
            <div class="table-responsive">
                <table class="table table-striped m-b-none" data-ride="datatables" id="table">
                    <thead>
                        <tr>
                            <th width="">ID</th>
                            <th width="">Nombre</th>
                            <th width="">CI / NIT</th>
                            <th width="">Dirección</th>
                            <th width="">Fecha</th>
                            <th width="">Menu</th>
                            <th width="">Precio</th>
                            <th width="">Cantidad</th>
                            <th width="">Total</th>
                            <th width="">Tipo</th>
                            <th width="">Estado</th>
                            <th width="150px">Acciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($orders as $order )
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->name }}</td>
                                <td>{{ $order->phone }}</td>
                                <td>{{ $order->address }}</td>
                                <td>{{ $order->delivery_date }}</td>
                                <td>{{ $order->product->product_name }}</td>
                                <td>{{ $order->product->price }}</td>
                                <td>{{ $order->quantity }}</td>
                                <td>{{ $order->product->price * $order->quantity }}</td>
                                <td>{{ $order->payment_option }}</td>
                                @if($order->order_status == 'Confirm')
                                    <td class="text-white bg-dark"><b style="border: 1px solid; padding: 1px 5px">{{ $order->order_status }}</b></td>
                                @elseif($order->order_status == 'Ready')
                                    <td class="text-warning"><b style="border: 1px solid; padding: 2px 5px">{{ $order->order_status }}</b></td>
                                @elseif($order->order_status == 'Send')
                                    <td class=""><b style="border: 1px solid blue; padding: 2px 5px; color:blue">{{ $order->order_status }}</b></td>
                                @elseif($order->order_status == 'Delivered')
                                    <td class="text-success"><b style="border: 1px solid; padding: 2px 5px">{{ $order->order_status }}</b></td>
                                @elseif($order->order_status == 'Returned')
                                    <td class="text-danger"><b style="border: 1px solid; padding: 2px 5px">{{ $order->order_status }}</b></td>
                                @elseif($order->order_status == 'Cancelled')
                                    <td class="text-dark"><b style="border: 1px solid; padding: 2px 5px">{{ $order->order_status }}</b></td>
                                @endif
                                <td>
                                    {{ Form::open(['route' => ['order.destroy', $order->id], 'method' => 'delete', 'style'=>'display:inline-block']) }}
                                    <button type="submit" class="btn btn-sm btn-icon btn-danger" onclick="return confirm('Are you sure you want to delete this?')" ><i class="fa fa-trash-o"></i></button>
                                    {{ Form::close() }}
                                    <a href="{{ route('order.edit',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-edit"></i></a>
                                    <a href="{{ route('order.show',$order->id) }}" class="btn btn-sm btn-icon btn-success"><i class="fa fa-print"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </section>
 </section>

@endsection

resources/views/order/new.blade.php
@extends('layouts.app')

@section('title')
    Nuevo pedido
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="index.html"><i class="fa fa-home"></i> Inicio</a></li>
            <li class="active">#</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Nuevo pedido</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                Formulario nuevo pedido
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>

            <div class="panel-body">
                {!! Form::open(array('route'=>'order.store')) !!}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Nombre</label>
                            {!! Form::text('name', '', ['placeholder'=>'Ingrese su nombre completo', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>CI /NIT</label>
                            {!! Form::text('phone', '', ['placeholder'=>'Ingrese su CI /NIT', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Dirección</label>
                            {!! Form::textarea('address', '', ['placeholder'=>'Ingrese su dirección', 'class'=>'form-control input-lg','rows'=>'3','required']) !!}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Fecha</label>
                            {!! Form::date('delivery_date', \Carbon\Carbon::now(), [ 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Menu</label>
                            {!! Form::select('product_id', $product, null, ['id'=>'product_id', 'class'=>'form-control m-b input-lg','required']) !!}
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Tipo</label>
                                    {!! Form::select('payment_option', array( 'Mesanine' => 'Mesanine', 'Para llevar' => 'Para llevar'), null, ['class'=>'form-control m-b input-lg','required']) !!}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Cantidad</label>
                                    {!! Form::number('quantity', '1', ['placeholder'=>'Ingrese cantidad', 'class'=>'form-control input-lg', 'required']) !!}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        <div class="row">
                            <div class="form-group">
                                <label class="col-sm-2">Estado</label>
                                <div class="col-sm-10 ">
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Confirm') !!}<i class="fa fa-circle-o fa-1x"></i>Confirmar </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Ready') !!}<i class="fa fa-circle-o"></i>Menu listo </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Send') !!}<i class="fa fa-circle-o"></i>En espera </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Delivered') !!}<i class="fa fa-circle-o"></i>Entregado </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Returned') !!}<i class="fa fa-circle-o"></i>Retornado </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Cancelled') !!}<i class="fa fa-circle-o"></i>Cancelado </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        {!! Form::submit('Enviar', [ 'class'=>'btn btn-default']) !!}
                    </div>
                {!! Form::close() !!}
            </div>

        </section>
    </section>
</section>

@endsection

resources/views/order/show.blade.php
@extends('layouts.app')

@section('title')
	Imprimir pedido
@endsection

@section('body')

<section class="vbox bg-white">
    <header class="header b-b b-light hidden-print">
        <button href="#" class="btn btn-sm btn-info pull-right" onClick="window.print();">Imprimir</button>
        <p>Recibo</p>
    </header>
    <section class="scrollable wrapper" id="print">
        <div class="row">
            <div class="col-xs-6">
                <h2 style="margin-top: 0px">MESTIZO <b>Servicio Web</b></h2>
                <p>Avenida Simón I. Patiño <br>
                    0000, Vinto<br>
                    Cochabamba, Bolivia
                </p>
            </div>
            <div class="col-xs-6 text-right">
                <h4>Recibo</h4>
            </div>
        </div>
        <div class="well m-t" style="margin-bottom: 50px">
            <div class="row">
                <div class="col-xs-6">
                    <strong>Para:</strong>
                    <h4>{{ $order->name }}</h4>
                    <p>
                        {{ $order->address }}
                    </p>
                    <b>CI / NIT: </b>{{ $order->phone }}
                </div>
                <div class="col-xs-6 text-right">
                    <p class="h4">#{{ $order->id }}</p>
                    <h5>Fecha: <strong>{{ $order->delivery_date }}</strong></h5>
                    <p class="m-t m-b">Pedido n°: <strong>{{ $order->id }}</strong></p>
                </div>
            </div>
        </div>
        <div class="line"></div>
        <table class="table">
            <thead>
            <tr>
                <th width="60">Cantidad</th>
                <th>Descripción</th>
                <th width="120">Precio</th>
                <th width="120">Total</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ $order->quantity }}</td>
                <td><b>{{ $order->product->id }}. {{ $order->product->product_name }}</b><br><small>{{ $order->product->product_details }}</small></td>
                <td class="">Bs. {{ $order->product->price }}</td>
                <td class="">Bs. {{ $order->product->price * $order->quantity }}</td>
            </tr>
            <tr>
                <td colspan="3" class="text-right"><strong>Subtotal</strong></td>
                <td>Bs. {{ $order->product->price * $order->quantity }}</td>
            </tr>
            <tr>
                <td colspan="3" class="text-right no-border"><strong>IVA</strong></td>
                <td>Bs. 0.00</td>
            </tr>
            <tr>
                <td colspan="3" class="text-right no-border"><strong>Total</strong></td>
                <td><strong>Bs. {{ $order->product->price * $order->quantity }}</strong></td>
            </tr>
            </tbody>
        </table>
        <div class="row">
            <div class="col-xs-8">
                <p style="text-align: justify;"><i> Mestizo, servicio de comidas</i></p><br><br>

                <p>Recibido: __________________ </p>
            </div>
        </div>
    </section>
</section>

@endsection